permissions:
  id-token: write

name: IaC

on:
  push:
    branches:
      - main

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: arn:aws:iam::211125728403:role/HetznerKubernetesGithubActionsRole
          aws-region: eu-central-1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3

      - name: Run terragrunt plan
        run: |
          cd live/
          terragrunt plan

      - name: Run terragrunt apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd live/
          terragrunt run --all --non-interactive apply
